### ISSUE TITLE
CodingStyle

### ISSUE THREAD

**Issue by dekablade01** [ineelam899/SurveyApp#1]
- `spacing` `link_break` `indent` are not consistent.

**Comment by ineelam899** [comment]
I go through all the app and make the codestyle consistence.

**Comment by dekablade01** [comment]
- When do you omit `self` and when you don't? `SurveyListViewController: 56,60`
- How do you decide to break the dictionary into multiple lines? `APIRouter: 36`

**Comment by ineelam899** [comment]
I fix this
