### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dekablade01** [ineelam899/SurveyApp#2]
- Lack of testing. Only `ViewModel` is tested. Services, Managers are not tested.

**Comment by ineelam899** [comment]
I have added more test cases

**Comment by dekablade01** [comment]
Cool, you're doing great for mocking those services for `ViewModel Tests` ✌️

But there some test cases remain for `ViewModel`, and running unit tests without internet fail the unit tests. `Unit tests` test does the implemented code works properly or not. It should not rely on the server-side. If you're making real network requests. What if the server is down, your unit test will always fail.

**Comment by ineelam899** [comment]
I run unit tests without internet. Its getting pass.

**Comment by dekablade01** [comment]
> I run unit tests without the internet. Its getting pass.

As I can see in `OAuthServiceTests` and `NetworkManagerTests`. You're using `NetworkManager()` which this class makes real network requests. Also, the `SurveyListViewModelTests` since `OAuthService` cannot be injected and always be initialized with `NetworkManager()` I'm not sure why it passes on your machine. 🤔

**Comment by dekablade01** [comment]
Hi @ineelam899, I'm pretty sure that running unit tests will fail. This is one of the most important parts of the assignment because `NetworkManager()` instance is for sending network requests. Unit tests should not rely on the server-side, it doesn't make sense if your code is working perfectly fine but when the-server is down your tests will fail. 



![picture](https://i.imgur.com/K4oGEMF.gif)

**Comment by ineelam899** [comment]
I reset my simulator and restart my macbook. I can see its getting failed now. I dont know what happen before at my machine

**Comment by ineelam899** [comment]
test getting pass if internet connection appear off

**Comment by ineelam899** [comment]
@Dekablade01 did you check my latest commit?
