### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by dekablade01** [ineelam899/SurveyApp#3]
- Load more doesn’t work.

**Comment by ineelam899** [comment]
I added pagination for api call

**Comment by dekablade01** [comment]
- When tapping on `reloadButton` it doesn't replace the whole collection but it keeps appending survey to the collection. This can be covered by the unit test. 

![2020-02-18 11 03 42](https://user-images.githubusercontent.com/6483170/74703033-86b9e080-523e-11ea-968f-61592380866a.gif)

**Comment by dekablade01** [comment]
- Page's inset doesn't work properly after stucks somewhere.
- `PageControl` is missing

![2020-02-18 11 06 59](https://user-images.githubusercontent.com/6483170/74703173-e912e100-523e-11ea-82e4-072ee8083533.gif)

**Comment by ineelam899** [comment]
I have added page control and fix the refresh button functionality.
