### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by dekablade01** [ineelam899/SurveyApp#4]
- `ApplicationCoordinator` is not needed since you navigate from `SurveyListViewController` to `TakeSurveyViewController` with storyboard. You can keep the default project’s configuration to launch the `Main.storyboard` . This is not consistent having routing logic in multiple places.
- `APIResult` should not be created since swift provide us `Swift.Result`
- Using `Error` in `String` lost many `Error` capabilities.
- Should `getOAuthToken` be in a survey service?
- `SurveyResponse` is not needed. Rather than creating a new Model to wrap Surveys, you can just pass `[Survey]` .
- `SurveyResponseMock` is not needed because there’s nothing is overridden. Then you can remove `open` and public from `Survey`
- Extensions should not be in the same file.
- `BaseViewController` is not needed.

**Comment by ineelam899** [comment]
Regarding ApplicationCoordinator, i did not remove because i am using that for injecting the properties. Rest of the feedback done

**Comment by dekablade01** [comment]
> Regarding ApplicationCoordinator, i did not remove because i am using that for injecting the properties. Rest of the feedback done

I did not mean you have to remove it. I meant you're using push viewController from code and storyboard. There should be only one navigation solution used. If there are 100+ viewControllers in the app, how can I find where did you implement the navigation for a specific view controller `storyboard` or `coordinator`

**Comment by dekablade01** [comment]
For `NetworkManager` rather than `completion: (Data?, NetworkError)` is it going to be better if you replace it with `Swift.Result<Data, NetworkError>` ?

**Comment by dekablade01** [comment]
Splitting `extension` by class doesn't help much. If you have 100+ of extension for a `UIViewController` class. You will have over 300 lines of code for `UIViewControllerExtensions`. Rather than using `UIViewControllerExtension.swift`, how about change it to `UIViewController+ShowErrorAlert.swift` ?

**Comment by dekablade01** [comment]
I don't understand why do you need `K.APIParameterKey` since you swift provides you an Encodable protocol. 🤔

**Comment by dekablade01** [comment]
I don't think you need `SurveyMock` because you're not overriding anything from `Survey`

**Comment by ineelam899** [comment]
Regarding K.APIParameterKey i am using that for the parameters of request. Rest am done.

**Comment by ineelam899** [comment]
I got your point for  K.APIParameterKey, Can we ignore this for now?
